version: '3.8'

services:
  jenkins:
    build:
      context: .devcontainer
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./target:/workspace/target
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose.yml:/workspace/docker-compose.yml  # Importante para acceso
    environment:
      # Variables para acceso Docker
      DOCKER_HOST: unix:///var/run/docker.sock
    restart: unless-stopped

  liberty:
    image: openliberty/open-liberty:25.0.0.5-full-java21-openj9-ubi-minimal
    container_name: liberty
    ports:
      - "9080:9080"
      - "9443:9443"
    volumes:
      - ./src/main/liberty/config:/opt/ol/wlp/usr/servers/defaultServer
      - ./target:/opt/ol/wlp/usr/servers/defaultServer/apps
    environment:
      DB_HOST: ${DB_HOST:-localhost}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-pupadb}
      DB_USER: ${DB_USER:-user}
      DB_PASSWORD: ${DB_PASSWORD:-pass}
    command: ["/opt/ol/wlp/bin/server", "run", "defaultServer"]
    restart: unless-stopped

volumes:
  jenkins_home: