version: '3.8'

services:
  jenkins:
    build:
      context: .devcontainer
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./target:/workspace/target
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  liberty:
    image: openliberty/open-liberty:25.0.0.5-full-java21-openj9-ubi-minimal
    container_name: liberty
    ports:
      - "9080:9080"
      - "9443:9443"
    volumes:
      # Montar configuración del servidor
      - ./src/main/liberty/config:/opt/ol/wlp/usr/servers/defaultServer
      # Montar WAR específico en lugar de todo el directorio target
      - ./target/PupaSv-1.0-SNAPSHOT.war:/opt/ol/wlp/usr/servers/defaultServer/apps/PupaSv.war
    command: ["/opt/ol/wlp/bin/server", "run", "defaultServer"]
    restart: unless-stopped

volumes:
  jenkins_home: